/**
 * FCC Snapshot Validation — Last-Known-Good gate (O9-F3.3P1-D3, Schritt 12).
 *
 * A candidate FCC provider snapshot (freshly generated by
 * `scripts/ad-hoc/fcc-catalog-sync.mjs`, or any future ingestion source) MUST
 * pass every check here before it is treated as usable. On any failure the
 * caller keeps whatever snapshot it already had — this module never returns
 * "valid" for an empty/malformed/suspicious candidate, and never repairs or
 * guesses a fix.
 *
 * Pure, DB-free, no IO — the caller supplies the candidate; this module never
 * reads a file or the network itself.
 */

import { mapFccProvider } from "./fccCatalog.ts";
import type { FccProviderSnapshotEntry } from "./fccProviderSnapshot.data.ts";

export interface FccSnapshotCandidate {
  schemaVersion: string;
  sourceRepo: string;
  sourceRevision: string;
  generatedAt: string;
  providers: readonly FccProviderSnapshotEntry[];
}

export type FccSnapshotValidationResult = { ok: true } | { ok: false; reason: string };

const REQUIRED_SOURCE_REPO = "Alishahryar1/free-claude-code";
const GIT_SHA_RE = /^[0-9a-f]{40}$/;

/** Clock-skew tolerance for `generatedAt` being in the future (minutes). */
const FUTURE_TOLERANCE_MS = 5 * 60 * 1000;

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function validateEntry(entry: unknown, index: number): string | null {
  if (typeof entry !== "object" || entry === null) {
    return `providers[${index}] is not an object`;
  }
  const candidate = entry as Partial<FccProviderSnapshotEntry>;
  if (!isNonEmptyString(candidate.fccProviderId)) {
    return `providers[${index}].fccProviderId missing or empty`;
  }
  if (!isNonEmptyString(candidate.displayName)) {
    return `providers[${index}].displayName missing or empty`;
  }
  if (candidate.authKind !== "configuration" && candidate.authKind !== "connected_account") {
    return `providers[${index}].authKind is not one of the known values`;
  }
  if (typeof candidate.local !== "boolean") {
    return `providers[${index}].local is not a boolean`;
  }
  if (candidate.defaultBaseUrl !== null && typeof candidate.defaultBaseUrl !== "string") {
    return `providers[${index}].defaultBaseUrl is neither null nor a string`;
  }
  if (candidate.credentialEnv !== null && typeof candidate.credentialEnv !== "string") {
    return `providers[${index}].credentialEnv is neither null nor a string`;
  }
  if (candidate.credentialUrl !== null && typeof candidate.credentialUrl !== "string") {
    return `providers[${index}].credentialUrl is neither null nor a string`;
  }
  return null;
}

/**
 * Validate a candidate snapshot's shape and content. Does NOT check mapping
 * conflicts against the live registry — use `validateFccSnapshotForAdoption`
 * for the full last-known-good gate before actually adopting a new snapshot.
 */
export function validateFccSnapshotShape(candidate: unknown): FccSnapshotValidationResult {
  if (typeof candidate !== "object" || candidate === null) {
    return { ok: false, reason: "candidate snapshot is not an object" };
  }
  const snapshot = candidate as Partial<FccSnapshotCandidate>;

  if (!isNonEmptyString(snapshot.schemaVersion)) {
    return { ok: false, reason: "schemaVersion missing or empty" };
  }
  if (snapshot.sourceRepo !== REQUIRED_SOURCE_REPO) {
    return {
      ok: false,
      reason: `sourceRepo must be "${REQUIRED_SOURCE_REPO}", got ${JSON.stringify(snapshot.sourceRepo)}`,
    };
  }
  if (!isNonEmptyString(snapshot.sourceRevision) || !GIT_SHA_RE.test(snapshot.sourceRevision)) {
    return { ok: false, reason: "sourceRevision is missing or not a full 40-char git SHA" };
  }
  if (!isNonEmptyString(snapshot.generatedAt)) {
    return { ok: false, reason: "generatedAt is missing or empty" };
  }
  const generatedAtMs = Date.parse(snapshot.generatedAt);
  if (Number.isNaN(generatedAtMs)) {
    return {
      ok: false,
      reason: `generatedAt is not a parseable timestamp: ${snapshot.generatedAt}`,
    };
  }
  if (generatedAtMs > Date.now() + FUTURE_TOLERANCE_MS) {
    return { ok: false, reason: "generatedAt is in the future" };
  }
  if (!Array.isArray(snapshot.providers) || snapshot.providers.length === 0) {
    return {
      ok: false,
      reason: "providers is missing, not an array, or empty — refusing an empty catalog as success",
    };
  }
  const seenIds = new Set<string>();
  for (let i = 0; i < snapshot.providers.length; i++) {
    const entryError = validateEntry(snapshot.providers[i], i);
    if (entryError) return { ok: false, reason: entryError };
    const id = (snapshot.providers[i] as FccProviderSnapshotEntry).fccProviderId;
    if (seenIds.has(id)) {
      return { ok: false, reason: `duplicate fccProviderId: ${id}` };
    }
    seenIds.add(id);
  }
  return { ok: true };
}

/**
 * Full last-known-good gate: shape validation PLUS a live check that no
 * provider in the candidate resolves to a `conflict` mapping against the
 * CURRENT OmniRoute registry (a newly-broken/newly-added alias is a reason to
 * hold the snapshot for review, not to silently adopt it).
 */
export function validateFccSnapshotForAdoption(candidate: unknown): FccSnapshotValidationResult {
  const shapeResult = validateFccSnapshotShape(candidate);
  if (!shapeResult.ok) return shapeResult;

  const snapshot = candidate as FccSnapshotCandidate;
  const conflicts = snapshot.providers
    .map((entry) => mapFccProvider(entry.fccProviderId))
    .filter((mapping) => mapping.status === "conflict");
  if (conflicts.length > 0) {
    return {
      ok: false,
      reason: `mapping conflict(s) present: ${conflicts.map((c) => c.fccProviderId).join(", ")}`,
    };
  }
  return { ok: true };
}
